version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://проасутп.рус
      - REACT_APP_API_URL=https://проасутп.рус
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge


