services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:3003"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000

networks:
  dev:
    driver: bridge


