version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge


