services:
  frontend:
    image: borissska/proasutp:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
      - PUBLIC_URL=https://xn--80a1acccihh.xn--p1acf
      - REACT_APP_API_URL=https://xn--80a1acccihh.xn--p1acf
    volumes:
      - ./ssl:/etc/nginx/ssl
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    driver: bridge


