services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:3003"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  frontend:
    build: ./client
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PUBLIC_URL=http://89.111.175.221:8080

networks:
  default:
    driver: bridge


