networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - dev


  frontend:
    build: ./client
    ports:
      - 3000:3000
    networks:
      - dev


